from odoo import models, fields, api
from odoo.exceptions import ValidationError
import re


class ResPartner(models.Model):
    _inherit = 'res.partner'

    company_custom_id = fields.Char(
        string='Auto Company ID',
        readonly=True,
        copy=False,
        index=True,
        tracking=True,
        help='Auto-generated Company ID (e.g., N001SMSTECHGARMENTS)',
    )

    contact_company_id_display = fields.Char(
        string='Contact Auto Company ID',
        compute='_compute_contact_company_id',
        store=False,
    )

    # ------------------------------------------------------------------
    # Constraint — country is mandatory for all company contacts
    # ------------------------------------------------------------------

    @api.constrains('is_company', 'country_id')
    def _check_company_country_required(self):
        for record in self:
            if record.is_company and not record.country_id:
                raise ValidationError(
                    f"Country is required for company \"{record.name or ''}\".\n"
                    "Please select a country before saving."
                )

    # ------------------------------------------------------------------
    # name_create — guard quick creates from many2one dropdowns
    # ------------------------------------------------------------------

    @api.model
    def name_create(self, name):
        """Prevent ID generation and bypass the country constraint for
        quick-creates from many2one fields (is_company stays False here).
        """
        record = self.with_context(
            skip_company_id_generation=True,
            default_is_company=False,   # don't inherit a company default
        ).create({'name': name})
        return record.id, record.display_name

    # ------------------------------------------------------------------
    # create — NO automatic ID generation.
    # ID is generated by the JS FormController after explicit Save.
    # ------------------------------------------------------------------

    @api.model_create_multi
    def create(self, vals_list):
        return super().create(vals_list)

    # ------------------------------------------------------------------
    # write — no ID-related triggers remain.
    # (company_type_selection has been removed; country changes after
    # an ID is assigned never regenerate — the ID is stable once set.)
    # ------------------------------------------------------------------

    # ------------------------------------------------------------------
    # action_generate_company_id
    # Called by the JS FormController after an explicit Save button click.
    # Also available as a fallback button in the view.
    # ------------------------------------------------------------------

    def action_generate_company_id(self):
        for record in self:
            if record.is_company and not record.company_custom_id:
                if not record.country_id:
                    raise ValidationError(
                        f"Cannot generate ID for \"{record.name or ''}\" "
                        "— Country is not set."
                    )
                record.sudo().write({
                    'company_custom_id': record._generate_company_id(
                        company_name=record.name or '',
                        country=record.country_id,
                    )
                })

    # ------------------------------------------------------------------
    # ID generation — prefix driven by country, not a radio button
    # ------------------------------------------------------------------

    def _generate_company_id(self, company_name='', country=None):
        """Generate a unique company ID.

        Prefix logic:
          country.code == 'IN'  (India)  →  'N'   e.g. N001SMSTECHGARMENTS
          any other country              →  'IN'  e.g. IN001ACMECORP
        """
        sequence = self.env['ir.sequence'].sudo().search(
            [('code', '=', 'res.partner.company.id')], limit=1
        )
        if not sequence:
            self.env['ir.sequence'].sudo().create({
                'name': 'Company Auto ID Sequence',
                'code': 'res.partner.company.id',
                'prefix': '',
                'suffix': '',
                'padding': 3,
                'number_increment': 1,
                'number_next_actual': 1,
            })
        else:
            sequence.sudo().write({'prefix': '', 'suffix': ''})

        seq_number = self.env['ir.sequence'].sudo().next_by_code(
            'res.partner.company.id'
        )

        clean_name = re.sub(r'\s+', '', company_name.upper())
        clean_name = re.sub(r'[^A-Z0-9]', '', clean_name)

        prefix = 'N' if (country and country.code == 'IN') else 'IN'
        return f'{prefix}{seq_number}{clean_name}'

    # ------------------------------------------------------------------
    # Compute
    # ------------------------------------------------------------------

    @api.depends(
        'parent_id', 'parent_id.company_custom_id',
        'is_company', 'company_custom_id',
    )
    def _compute_contact_company_id(self):
        for rec in self:
            if rec.is_company:
                rec.contact_company_id_display = rec.company_custom_id or ''
            elif rec.parent_id and rec.parent_id.company_custom_id:
                rec.contact_company_id_display = rec.parent_id.company_custom_id
            else:
                rec.contact_company_id_display = ''