{
    'name': 'Case Study',
    'version': '1.0',
    'license': 'LGPL-3',
    'summary': 'Manage Case Studies',
    'description': 'A module to manage case studies',
    'category': 'Custom',
    'author': 'Your Name',
    'depends': ['base', 'mail','hr','project',
        'hr_timesheet',],
    'data': [
        'security/ir.model.access.csv',
        'security/case_study_rules.xml',
        'data/case_study_sequence.xml',
        'data/case_study_stages_data.xml',
        'views/case_study_views.xml',
    ],
    'installable': True,
    'application': True,
}