{
    'name': 'Custom Manufacturing',
    'version': '19.0.2.0.0',
    'category': 'Manufacturing',
    'summary': 'Assembly + Production manufacturing with component tracking, serial numbers, warranty, and cost analysis',
    'author': 'Internal ERP Team',
    'depends': [
        'base',
        'mrp',
        'stock',
        'product',
        'mail',
        'account',
        'stock_account',
        #'sales',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/manufacturing_sequence.xml',
        'data/manufacturing_cron.xml',
        'wizard/mrp_serial_wizard_views.xml',
        'views/mrp_bom_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_warranty_views.xml',
        'views/manufacturing_menu.xml',
        'report/mrp_job_card_report.xml',
        'report/mrp_warranty_certificate_report.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}