from odoo import api, fields, models, _
from odoo.exceptions import UserError


class CrmLead(models.Model):
    _inherit = 'crm.lead'

    # ── Fields ──────────────────────────────────────────────────────────────

    is_converted = fields.Boolean(
        string='Converted to Project',
        default=False,
        copy=False,
        help='Set to True after this query has been converted to a project. '
             'Once set, the record becomes read-only and cannot be converted again.',
    )

    project_id = fields.Many2one(
        'project.project',
        string='Linked Project',
        readonly=True,
        copy=False,
        help='The project that was created from this CRM query.',
    )

    project_count = fields.Integer(
        string='Project Count',
        compute='_compute_project_count',
    )

    # ── Compute ─────────────────────────────────────────────────────────────

    @api.depends('project_id')
    def _compute_project_count(self):
        for lead in self:
            lead.project_count = 1 if lead.project_id else 0

    # ── Business Logic ───────────────────────────────────────────────────────

    def action_convert_to_project(self):
        """
        Manual one-time conversion of a Won CRM opportunity into a Project.

        Project number is now auto-generated by project.project's create()
        override — no need to call the sequence here.
        """
        self.ensure_one()

        # Guard 1: opportunity must be Won
        if not self.stage_id.is_won:
            raise UserError(
                _('Only Won opportunities can be converted to a project.\n\n'
                  'Please mark this opportunity as Won before converting.')
            )

        # Guard 2: prevent duplicate conversion
        if self.is_converted:
            raise UserError(
                _('This query has already been converted to a project. '
                  'No further conversion is allowed.')
            )

        # Build project values — project_number assigned automatically by create()
        project_vals = {
            'name': self.name,
            'partner_id': self.partner_id.id if self.partner_id else False,
            'description': self.description or '',
            'crm_lead_id': self.id,
            # team_id intentionally omitted — user can assign it on the project form
        }

        project = self.env['project.project'].create(project_vals)

        self.sudo().write({
            'is_converted': True,
            'project_id': project.id,
        })

        return {
            'type': 'ir.actions.act_window',
            'name': _('Project'),
            'res_model': 'project.project',
            'res_id': project.id,
            'view_mode': 'form',
            'target': 'current',
        }

    def action_open_linked_project(self):
        """Smart-button action: open the linked project."""
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'name': _('Project'),
            'res_model': 'project.project',
            'res_id': self.project_id.id,
            'view_mode': 'form',
            'target': 'current',
        }

    def unlink(self):
        if any(lead.is_converted for lead in self):
            raise UserError(
                _('Converted opportunities cannot be deleted. '
                  'They must be kept for traceability with the linked project.')
            )
        return super().unlink()

    def write(self, vals):
        if 'active' in vals and not vals['active']:
            if any(lead.is_converted for lead in self):
                raise UserError(
                    _('Converted opportunities cannot be archived. '
                      'They must remain visible for traceability.')
                )
        return super().write(vals)